version: '2'
services:
  map:
    build:
      context : ./map
      dockerfile : Dockerfile
    command : [bash,/scripts/main.sh]
    volumes : 
      - /WordCountPipe/split/outbox:/inbox
      - /WordCountPipe/map/outbox:/outbox
    tty : true

  combine:
    build: 
      context : ./combine
      dockerfile : Dockerfile
    command : [bash,/scripts/main.sh]
    volumes : 
      - /WordCountPipe/map/outbox/processed:/inbox
      - /WordCountPipe/combine/outbox:/outbox
    tty : true

  shuffle_and_sort:
    build:
      context : ./shuffle_and_sort
      dockerfile : Dockerfile
    command : [bash,/scripts/main.sh]
    volumes :
      - /WordCountPipe/combine/outbox/processed:/inbox
      - /WordCountPipe/shuffle_and_sort/outbox:/outbox
    tty : true

